import {
  Injectable,
  Logger,
  ServiceUnavailableException,
  UnauthorizedException,
} from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import {
  IPaymentProvider,
  PaymentSessionResult,
} from './payment-provider.interface';
import { lastValueFrom } from 'rxjs';
import { createHash, timingSafeEqual } from 'crypto';
import { PaymentsService } from '../payments.service';
import { decryptConfigValues } from '../shared/utils/encryption.util';
import { PaymentStatus } from '../shared/enums/payment-status.enum';
import { WebhookMoyasarDto } from '../shared/dto/webhook-moyasar.dto';
/**
 * Moyasar payment provider implementation.
 * Handles secure communication with Moyasar's API for session creation,
 * payment verification, and invoice retrieval.
 */
@Injectable()
export class MoyasarProvider implements IPaymentProvider {
  private readonly logger = new Logger(MoyasarProvider.name);

  constructor(
    private readonly httpService: HttpService,
    private readonly paymentsService: PaymentsService,
  ) {}

  /**
   * Loads the decrypted Moyasar `secretConfig` from the database, even while
   * payments or the method are disabled (in-flight payments must still verify).
   *
   * @returns The decrypted config, or an empty object when none is stored.
   */
  private async getSecretConfig(): Promise<Record<string, string>> {
    const moyasarMethod =
      await this.paymentsService.findCredentialsByCode('moyasar');
    return moyasarMethod?.secretConfig
      ? (decryptConfigValues(moyasarMethod.secretConfig) as Record<
          string,
          string
        >)
      : {};
  }

  /**
   * Retrieves the Moyasar secret key securely from the database configuration.
   * If the configuration is not found in the database, it falls back to the environment variable.
   *
   * @returns {Promise<string>} A promise that resolves to the decrypted Moyasar secret key.
   * @private
   */
  private async getSecretKey(): Promise<string> {
    const decryptedConfig = await this.getSecretConfig();
    return (
      decryptedConfig.MOYASAR_SECRET_KEY || process.env.MOYASAR_SECRET_KEY || ''
    );
  }

  /**
   * Initiates a payment session for a given order.
   * Note: For Moyasar, the actual payment form is typically rendered on the client-side.
   * This method primarily constructs the callback URL to redirect the user to the checkout page.
   *
   * @param {string} orderId - The unique identifier of the order.
   * @param {number} _amount - The payment amount (handled by the frontend form).
   * @param {string} _currency - The payment currency (handled by the frontend form).
   * @param {string} _userEmail - The customer's email address (handled by the frontend form).
   * @param {Record<string, unknown>} [_metadata] - Optional additional metadata for the payment.
   * @returns {Promise<PaymentSessionResult>} A promise containing the payment URL and pending status.
   */

  /* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/require-await */
  async createSession(
    orderId: string,
    _amount: number,
    _currency: string,
    _userEmail: string,
    _metadata?: Record<string, unknown>,
  ): Promise<PaymentSessionResult> {
    /* eslint-enable @typescript-eslint/no-unused-vars, @typescript-eslint/require-await */
    try {
      const callbackUrl = `${process.env.CLIENT_URL || 'http://localhost:3000'}/ar/checkout/moyasar?orderId=${orderId}`;

      return {
        providerPaymentId: undefined, // Will be generated by frontend Moyasar Form
        paymentUrl: callbackUrl,
        status: PaymentStatus.PENDING,
      };
    } catch (err: unknown) {
      const error = err as Error;
      this.logger.error(
        `Moyasar session creation failed for order ${orderId}: ${error.message}`,
      );
      return {
        status: PaymentStatus.FAILED,
        errorMessage: error.message,
      };
    }
  }

  /**
   * Fetches the details of a specific payment directly from the Moyasar API.
   * This is used to securely verify the payment status after a transaction attempt
   * or upon receiving a webhook, ensuring the system cannot be spoofed.
   *
   * @param {string} paymentId - The unique payment identifier provided by Moyasar.
   * @returns {Promise<Record<string, unknown> | null>} The payment details, or null when Moyasar has no such payment (404).
   * @throws {ServiceUnavailableException} On any other failure (network, timeout, 5xx, rejected credentials),
   * so the webhook answers 5xx and Moyasar redelivers instead of the event being lost.
   */
  async fetchPayment(
    paymentId: string,
  ): Promise<Record<string, unknown> | null> {
    const MOYASAR_SECRET_KEY = await this.getSecretKey();
    const authHeader = `Basic ${Buffer.from(`${MOYASAR_SECRET_KEY}:`).toString('base64')}`;

    try {
      const response = await lastValueFrom(
        this.httpService.get(
          // Encoded so an id can never change the API path (e.g. '../invoices/x').
          `https://api.moyasar.com/v1/payments/${encodeURIComponent(paymentId)}`,
          {
            headers: {
              Authorization: authHeader,
            },
          },
        ),
      );
      return response.data as Record<string, unknown>;
    } catch (err: unknown) {
      const error = err as Error & { response?: { status?: number } };
      this.logger.error(
        `Failed to fetch Moyasar payment ${paymentId}: ${error.message}`,
      );
      if (error.response?.status === 404) return null;
      throw new ServiceUnavailableException(
        'Payment provider is temporarily unavailable',
      );
    }
  }

  /**
   * Fetches the details of a specific invoice directly from the Moyasar API.
   *
   * @param {string} invoiceId - The unique invoice identifier provided by Moyasar.
   * @returns {Promise<Record<string, unknown> | null>} A promise that resolves to the invoice details object, or null if the request fails.
   */
  async fetchInvoice(
    invoiceId: string,
  ): Promise<Record<string, unknown> | null> {
    const MOYASAR_SECRET_KEY = await this.getSecretKey();
    const authHeader = `Basic ${Buffer.from(`${MOYASAR_SECRET_KEY}:`).toString('base64')}`;

    try {
      const response = await lastValueFrom(
        this.httpService.get(
          `https://api.moyasar.com/v1/invoices/${invoiceId}`,
          {
            headers: {
              Authorization: authHeader,
            },
          },
        ),
      );
      return response.data as Record<string, unknown>;
    } catch (err: unknown) {
      const error = err as Error;
      this.logger.error(
        `Failed to fetch Moyasar invoice ${invoiceId}: ${error.message}`,
      );
      return null;
    }
  }

  /**
   * Verifies the authenticity of a Moyasar webhook payload using the secret token.
   * Returns the payment ID from the payload if valid.
   *
   * The secret is mandatory: without one every webhook is rejected rather than
   * accepted unauthenticated. Compared in constant time.
   *
   * @param payload - The webhook payload received from Moyasar.
   * @returns The extracted payment ID, or undefined if not present.
   * @throws {UnauthorizedException} If no secret is configured or the token does not match.
   */
  async verifyWebhook(payload: WebhookMoyasarDto): Promise<string | undefined> {
    const decryptedConfig = await this.getSecretConfig();
    const secret =
      decryptedConfig.MOYASAR_WEBHOOK_SECRET ||
      process.env.MOYASAR_WEBHOOK_SECRET;

    if (!secret) {
      this.logger.error(
        'MOYASAR_WEBHOOK_SECRET is not configured (payment method secretConfig or env): rejecting webhook',
      );
      throw new UnauthorizedException('Invalid Webhook Secret Token');
    }

    if (!secretsMatch(payload.secret_token ?? '', secret)) {
      this.logger.error('Invalid Webhook Secret Token received');
      throw new UnauthorizedException('Invalid Webhook Secret Token');
    }

    return payload?.data?.id as string | undefined;
  }
}

/**
 * Constant-time comparison. Both sides are hashed first so their lengths are
 * equal (timingSafeEqual requires it) and the secret's length does not leak.
 */
function secretsMatch(received: string, expected: string): boolean {
  const digest = (value: string) => createHash('sha256').update(value).digest();
  return timingSafeEqual(digest(received), digest(expected));
}
