import { Injectable, Logger } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import {
  IPaymentProvider,
  PaymentSessionResult,
} from './payment-provider.interface';
import { lastValueFrom } from 'rxjs';

@Injectable()
export class MoyasarProvider implements IPaymentProvider {
  private readonly logger = new Logger(MoyasarProvider.name);

  constructor(private readonly httpService: HttpService) {}

  /* eslint-disable @typescript-eslint/no-unused-vars */
  // eslint-disable-next-line @typescript-eslint/require-await
  async createSession(
    orderId: string,
    _amount: number,
    _currency: string,
    _userEmail: string,
    _metadata?: Record<string, unknown>,
  ): Promise<PaymentSessionResult> {
    /* eslint-enable @typescript-eslint/no-unused-vars */
    try {
      const callbackUrl = `${process.env.CLIENT_URL || 'http://localhost:3000'}/ar/checkout/moyasar?orderId=${orderId}`;

      return {
        providerPaymentId: undefined, // Will be generated by frontend Moyasar Form
        paymentUrl: callbackUrl,
        status: 'PENDING',
      };
    } catch (err: unknown) {
      const error = err as Error;
      this.logger.error(
        `Moyasar session creation failed for order ${orderId}: ${error.message}`,
      );
      return {
        status: 'FAILED',
        errorMessage: error.message,
      };
    }
  }

  async fetchPayment(
    paymentId: string,
  ): Promise<Record<string, unknown> | null> {
    const MOYASAR_SECRET_KEY = process.env.MOYASAR_SECRET_KEY;
    const authHeader = `Basic ${Buffer.from(`${MOYASAR_SECRET_KEY}:`).toString('base64')}`;

    try {
      const response = await lastValueFrom(
        this.httpService.get(
          `https://api.moyasar.com/v1/payments/${paymentId}`,
          {
            headers: {
              Authorization: authHeader,
            },
          },
        ),
      );
      return response.data as Record<string, unknown>;
    } catch (err: unknown) {
      const error = err as Error;
      this.logger.error(
        `Failed to fetch Moyasar payment ${paymentId}: ${error.message}`,
      );
      return null;
    }
  }

  async fetchInvoice(
    invoiceId: string,
  ): Promise<Record<string, unknown> | null> {
    const MOYASAR_SECRET_KEY = process.env.MOYASAR_SECRET_KEY;
    const authHeader = `Basic ${Buffer.from(`${MOYASAR_SECRET_KEY}:`).toString('base64')}`;

    try {
      const response = await lastValueFrom(
        this.httpService.get(
          `https://api.moyasar.com/v1/invoices/${invoiceId}`,
          {
            headers: {
              Authorization: authHeader,
            },
          },
        ),
      );
      return response.data as Record<string, unknown>;
    } catch (err: unknown) {
      const error = err as Error;
      this.logger.error(
        `Failed to fetch Moyasar invoice ${invoiceId}: ${error.message}`,
      );
      return null;
    }
  }
}
